<?xml version="1.0"?>
<robot name="paul" xmlns:xacro="http://ros.org/wiki/xacro">


  <joint name="camera_base_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${bodylen/2} 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_base_link"/>
  </joint>

  
  <!-- Camera base-->
  <link name="camera_base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.03 0.175 0.033"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.03 0.175 0.033"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <mass value="0.166" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
 


  <!-- Camera --> 
<xacro:macro name="Zedcamera" params="prefix reflect">
	
  <joint name="camera_${prefix}_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.015 ${reflect*0.08} 0" rpy="0 0 0"/>
    <parent link="camera_base_link"/>
    <child link="camera_${prefix}_link"/>
  </joint>

  <link name="camera_${prefix}_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="0.166" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
 </xacro:macro>
  
  <xacro:Zedcamera prefix="right" reflect="-1" />
  <xacro:Zedcamera prefix="left" reflect="1" />

 
  <!-- camera -->
  <gazebo reference="camera_left_link">
    <sensor type="multicamera" name="stereo_camera">
      <update_rate>30.0</update_rate>
      <camera name="left">
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
          <hfov>110</hfov>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <camera name="right">
        <pose>0 -0.16 0 0 0 0</pose>
        <image>
          <width>1280</width>
          <height>720</height>
          <hfov>110</hfov>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>stereo_camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>left_cam_rotated</frameName>
        <rightFrameName>right_cam_rotated</rightFrameName>
        <hackBaseline>0.16</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
    <material>Gazebo/Orange</material>
  </gazebo>
  <gazebo reference="camera_right_link">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="camera_base_link">
    <material>Gazebo/Black</material>
  </gazebo>


  <gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>camera_left_link</bodyName>
      <topicName>imu/data</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>20.0</updateRate>
    </plugin>
  </gazebo>

</robot>
