global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.5
  publish_frequency: 0.5
  static_map: false 
  width: 40.0 
  height: 40.0 
  origin_x: -20.0 
  origin_y: -20.0

